postsubmits:
  kubernetes/k8s.io:
    - name: post-k8sio-push-image-octodns-docker
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-k8s-infra-k8sio, sig-k8s-infra-gcb
      decorate: true
      run_if_changed: "^dns/octodns-docker/"
      branches:
        - ^main$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-staging-test-infra/image-builder:v20211014-7ca1952a94
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR
              # images are pushed to.
              - --project=k8s-staging-infra-tools
              - --scratch-bucket=gs://k8s-staging-infra-tools-gcb
              - --env-passthrough=PULL_BASE_REF
              - dns/octodns-docker
    - name: post-k8sio-push-image-k8s-infra
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-k8s-infra-k8sio, sig-k8s-infra-gcb
      decorate: true
      run_if_changed: "^images/k8s-infra/"
      branches:
        - ^main$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-staging-test-infra/image-builder:v20211014-7ca1952a94
            command:
              - /run.sh
            args:
              - --project=k8s-staging-infra-tools
              - --scratch-bucket=gs://k8s-staging-infra-tools-gcb
              - --env-passthrough=PULL_BASE_REF
              - images/k8s-infra
