postsubmits:
  kubernetes-sigs/k8s-gsm-tools:
    - name: post-k8s-gsm-tools-push-images
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-testing-images, sig-k8s-infra-gcb
        testgrid-tab-name: k8s-gsm-tools
      decorate: true
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-staging-test-infra/image-builder:v20211014-7ca1952a94
            command:
              - /run.sh
            args:
              - --project=k8s-staging-k8s-gsm-tools
              - --scratch-bucket=gs://k8s-staging-k8s-gsm-tools-gcb
              - --env-passthrough=PULL_BASE_REF
              - --build-dir=.
              - images/
            env:
              - name: LOG_TO_STDOUT
                value: "y"
