presubmits:
  kubernetes-sigs/apiserver-network-proxy:
  - name: pull-apiserver-network-proxy-test
    always_run: true
    skip_report: false
    decorate: true
    path_alias: sigs.k8s.io/apiserver-network-proxy
    spec:
      containers:
      - image: golang:1.13
        command:
        - make
        args:
        - test
    annotations:
      testgrid-dashboards: sig-cloud-provider-apiserver-network-proxy
      testgrid-tab-name: pr-test
      description: Tests the apiserver-network-proxy
  - name: pull-apiserver-network-proxy-docker-build-all
    always_run: true
    skip_report: false
    decorate: true
    path_alias: sigs.k8s.io/apiserver-network-proxy
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211014-794b7e0910-master
        command:
        - "runner.sh"
        args:
        - make
        - docker-build-all
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-cloud-provider-apiserver-network-proxy
      testgrid-tab-name: pr-docker-build-all
      description: Build via Docker all the arch release for the apiserver-network-proxy
  - name: pull-apiserver-network-proxy-make-lint
    always_run: true
    skip_report: false
    decorate: true
    path_alias: sigs.k8s.io/apiserver-network-proxy
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211014-794b7e0910-master
        command:
        - "runner.sh"
        args:
        - make
        - lint
    annotations:
      testgrid-dashboards: sig-cloud-provider-apiserver-network-proxy
      testgrid-tab-name: pr-make-lint
      description: Run lint target for the apiserver-network-proxy
